commands:
  no-args: "&bSpecifica un &fargomento&b!"
  unknown-arg: "&bArgomento &fnon riconosciuto&b!"
  no-perms: "&bNon hai il &fpermesso &bdi &feseguire &bquesto comando!"


events:
  player-death: "&f%s% &bè morto, ne rimangono &f%d%"
  point: "&b+&f1 &bPunto"
  died: "&bSei &fmorto&b!"

locations:
  spawn: ""
  lobby: ""
  corner-a: ""
  corner-b: ""

settings:
  death-y: 30