no-args: "&bSpecifica un &fargomento&b!"
unknown-arg: "&bArgomento &fnon riconosciuto&b!"
no-perms: "&bHai bisogno del permesso &f%s &bper eseguire questo comando!"
not-player: "&bDevi essere un &fgiocatore &bper eseguire questo comando!"
locations-invalid: "&bLe locazioni sono &finvalide&b!"
not-enough: "&bNon ci sono abbastanza giocatori per iniziare la partita!"

player-death: "&f%s &bè morto, ne rimangono &f%s"
point: "&b+&f1 &bCoin"
died: "&bSei &fmorto&b!"

reloaded: "&bConfigurazione &fricaricata&b!"
game-end: "&bPartita &fterminata&b!"
status-format: "&bLo stato attuale del game è %s"

error: "&bNon puoi impostare questo stato durante %s"
status-set: "&bImpostato lo stato a %s!"
difficulty-announcement: "&bNuova difficoltà impostata su %s&b!"
block-announcement: "&bIl prossimo colore sarà %s&b!"

cancel-announce: "&bCountdown terminato, non ci sono abbastanza giocatori, attendiamo."
winner-announce: "&bIl vincitore della partita è &f%s&b con &f%s punti&b!"
floor-announce: "&bIl terreno si romperà in &f%s&b!"
timer-announce: "&bLa partita inizerà in &f%s&b!"

spawn-set: "&bImpostato correttamente lo &fspawn!"
lobby-set: "&bImpostata correttamente la &flobby!"
locations-set: "&bImpostata correttamente la &ftavola!"

axe-add: "&bAggiunto lo &fstrumento di selezione &bal tuo inventario!"
position-set: "&bPosizione Elaborata &fX: %s - Z: %s"

block-load: "Caricato con successo %s con data %s!"

axe-name: "&bSelection Tool"
kick-message: "&bPartita Terminata!"

round-time: 15
death-y: 30
refill-time: 5

min-players: 20
countdown: 10