no-args: "&bSpecifica un &fargomento&b!"
unknown-arg: "&bArgomento &fnon riconosciuto&b!"
no-perms: "&bNon hai il &fpermesso &bdi &feseguire &bquesto comando!"

player-death: "&f%s &bè morto, ne rimangono &f%d"
point: "&b+&f1 &bPunto"
died: "&bSei &fmorto&b!"

reloaded: "&bConfigurazione &fricaricata&b!"
game-end: "&bPartita &fterminata&b!"
status-format: "&bLo stato attuale del game è %s"

error: "&bNon puoi impostare questo stato durante %s"
status-set: "&bImpostato lo stato a %s!"
difficulty-announcement: "&bNuova difficoltà impostata su %s&b!"
block-announcement: "&bIl prossimo colore sarà %s&b!"

winner-announce: "&bIl vincitore della partita è &f%s&b con &f%d% punti&b!"
floor-announce: "&bIl terreno si romperà in &f%d&b!"
timer-announce: "&bLa partita inizerà in &f%d&b!"

kick-message: "&bPartita Terminata!"
stop-time: 15

death-y: 30
refill-time: 5
countdown: 15
