commands:
  no-args: "&bSpecifica un &fargomento&b!"
  unknown-arg: "&bArgomento &fnon riconosciuto&b!"
  no-perms: "&bNon hai il &fpermesso &bdi &feseguire &bquesto comando!"


settings:
  death-y: 30
  corner-a: ""
  corner-b: ""